### ISSUE TITLE
duplicate of chai-subset?

### ISSUE THREAD

**Issue by mlippens** [JamesMGreene/chai-deep-match#1]
This seems to be a duplicate plugin of http://chaijs.com/plugins/chai-subset/ or am I missing something?

**Comment by JamesMGreene** [comment]
Same intentions, I suppose... I wasn't aware the other existed.

Anyway: different API, different implementation. Mine is also currently only suitable for use on Node.js.

**Comment by marcelowa** [comment]
I just tried it, and although it is similar to chai-subset the diff output makes more sense to me with this library

**Comment by JamesMGreene** [comment]
Thanks, @marcelowa! I put some thought into how to present the diff, so I'm glad others appreciate it like I do. 👍
