### ISSUE TITLE
Upgrade peer dependency to chai v4

### ISSUE THREAD

**Issue by vcarel** [JamesMGreene/chai-deep-match#5]
When installing chai-deep-match latest, we get:

    warning "chai-deep-match@1.0.2" has incorrect peer dependency "chai@>=2.1.2 <4"

However it seems to work fine with chai 4.*

**Comment by benderTheCrime** [comment]
@JamesMGreene looks like this has been around for a while, I'm getting this warning as well. Can we upgrade the peerDependency here?

**Comment by JamesMGreene** [comment]
Published with `v1.1.0`. Thanks!
